# POST http://localhost:3000/reports
# Content-Type: application/json

# {
#     "price": 10000,
#     "make": "BMW",
#     "model": "M7",
#     "year": 1980, 
#     "mileage": 100000,
#     "lng" : 23,
#     "lat" : 10

# }

## Approve an existing report
# PATCH http://localhost:3000/reports/5
# Content-Type: application/json

# {
#     "approved": true
# }

## get estimate for a car
GET http://localhost:3000/reports/?make=BMW&model=M7&lng=23&lat=10&mileage=10000&year=2012
